import Head from 'next/head'
import Image from 'next/image'
import Header from '@components/header'
import Navigation from '@components/navigation'
import { InferGetStaticPropsType } from 'next'
import { getPostList } from '@shared/util'
import Link from 'next/link'

type PostList = String[]

function Home({ posts }: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigation />
        <Header />
        {posts.length > 0 && (
          <ul>
            {posts.map((slug) => (
              <li key={slug.toString()}>
                <Link href={`post/${slug}`}>
                  <a>
                    {slug.replace(/-/g, ' ')}
                  </a>
                </Link>
              </li>
            ))}
          </ul>
        )}
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  const posts:PostList = getPostList();

  return {
      props: {
        posts
      }
  };
}

export default Home;